# The data about elements
# 0 - Atomic number
# 1 - Symbol
# 2 - Name
# 3 - Etymology
# 4, 5 - Group, period
# 6 - block
# 7 - atomic weight

ELEMENTS = [
    [1, 	"H",	"Hydrogen",	        "Greek elements hydro- and -gen, 'water-forming'",
        1,	1,	"s-block",	"1.0080"],
    [2, 	"He",	"Helium",	        "Greek hḗlios, 'sun'",
        18,	1,	"s-block",	"4.0026"],
    [3, 	"Li",	"Lithium",	        "Greek líthos, 'stone'",
        1,	2,	"s-block",	"6.94"],
    [4, 	"Be",	"Beryllium",	    "Beryl, a mineral (ultimately from the name of Belur in southern India)",
        2,	2,	"s-block",	"9.0122"],
    [5, 	"B",	"Boron",	        "Borax, a mineral (from Arabic bawraq, Middle Persian *bōrag)",
        13,	2,	"p-block",	"10.81"],
    [6, 	"C",	"Carbon",	        "Latin carbo, 'coal'",
        14,	2,	"p-block",	"12.011"],
    [7, 	"N",	"Nitrogen",	        "Greek nítron and -gen, 'niter-forming'",
        15,	2,	"p-block",	"14.007"],
    [8, 	"O",	"Oxygen",	        "Greek oxy- and -gen, 'acid-forming'",
        16,	2,	"p-block",	"15.999"],
    [9, 	"F",	"Fluorine",	        "Latin fluere, 'to flow'",
        17,	2,	"p-block",	"18.998"],
    [10, 	"Ne",	"Neon",	            "Greek néon, 'new'",
        18,	2,	"p-block",	"20.180"],
    [11, 	"Na",	"Sodium",	        "English (from medieval Latin) soda. Symbol Na is derived from New Latin natrium, coined from German Natron, 'natron'",
        1,	3,	"s-block",	"22.990"],
    [12, 	"Mg",	"Magnesium",	    "Magnesia, a district of Eastern Thessaly in Greece",
        2,	3,	"s-block",	"24.305"],
    [13, 	"Al",	"Aluminium",	    "Alumina, from Latin alumen (gen. aluminis), 'bitter salt, alum'",
        13,	3,	"p-block",	"26.982"],
    [14, 	"Si",	"Silicon",	        "Latin silex, 'flint' (originally silicium)",
        14,	3,	"p-block",	"28.085"],
    [15, 	"P",	"Phosphorus",	    "Greek phōsphóros, 'light-bearing'",
        15,	3,	"p-block",	"30.974"],
    [16, 	"S",	"Sulfur",	        "Latin sulphur, 'brimstone'",
        16,	3,	"p-block",	"32.06"],
    [17, 	"Cl",	"Chlorine",	        "Greek chlōrós, 'greenish yellow'",
        17,	3,	"p-block",	"35.45"],
    [18, 	"Ar",	"Argon",	        "Greek argós, 'idle' (because of its inertness)",
        18,	3,	"p-block",	"39.95"],
    [19, 	"K",	"Potassium",	    "New Latin potassa, 'potash', itself from pot and ash. Symbol K is derived from Latin kalium",
        1,	4,	"s-block",	"39.098"],
    [20, 	"Ca",	"Calcium",	        "Latin calx, 'lime'",
        2,	4,	"s-block",	"40.078"],
    [21, 	"Sc",	"Scandium",	        "Latin Scandia, 'Scandinavia'",
        3,	4,	"d-block",	"44.956"],
    [22, 	"Ti",	"Titanium",	        "Titans, the sons of the Earth goddess of Greek mythology",
        4,	4,	"d-block",	"47.867"],
    [23, 	"V",	"Vanadium",	        "Vanadis, an Old Norse name for the Scandinavian goddess Freyja",
        5,	4,	"d-block",	"50.942"],
    [24, 	"Cr",	"Chromium",	        "Greek chróma, 'colour'",
        6,	4,	"d-block",	"51.996"],
    [25, 	"Mn",	"Manganese",	    "Corrupted from magnesia negra",
        7,	4,	"d-block",	"54.938"],
    [26, 	"Fe",	"Iron",	            "English word, from Proto-Celtic *īsarnom ('iron'), from a root meaning 'blood'. Symbol Fe is derived from Latin ferrum",
        8,	4,	"d-block",	"55.845"],
    [27, 	"Co",	"Cobalt",	        "German Kobold, 'goblin'",
        9,	4,	"d-block",	"58.933"],
    [28, 	"Ni",	"Nickel",	        "Nickel, a mischievous sprite of German miner mythology",
        10,	4,	"d-block",	"58.693"],
    [29, 	"Cu",	"Copper",	        "English word, from Latin cuprum, from Ancient Greek Kýpros 'Cyprus'",
        11,	4,	"d-block",	"63.546"],
    [30, 	"Zn",	"Zinc",	            "Most likely from German Zinke, 'prong' or 'tooth', though some suggest Persian sang, 'stone'",
        12,	4,	"d-block",	"65.38"],
    [31, 	"Ga",	"Gallium",	        "Latin Gallia, 'France'",
        13,	4,	"p-block",	"69.723"],
    [32, 	"Ge",	"Germanium",	    "Latin Germania, 'Germany'",
        14,	4,	"p-block",	"72.630"],
    [33, 	"As",	"Arsenic",	        "French arsenic, from Greek arsenikón 'yellow arsenic' (influenced by arsenikós, 'masculine' or 'virile'), from a West Asian wanderword ultimately from Old Iranian *zarniya-ka, 'golden'",
        15,	4,	"p-block",	"74.922"],
    [34, 	"Se",	"Selenium",	        "Greek selḗnē, 'moon'",
        16,	4,	"p-block",	"78.971"],
    [35, 	"Br",	"Bromine",	        "Greek brômos, 'stench'",
        17,	4,	"p-block",	"79.904"],
    [36, 	"Kr",	"Krypton",	        "Greek kryptós, 'hidden'",
        18,	4,	"p-block",	"83.798"],
    [37, 	"Rb",	"Rubidium",	        "Latin rubidus, 'deep red'",
        1,	5,	"s-block",	"85.468"],
    [38, 	"Sr",	"Strontium",        "Strontian, a village in Scotland, where it was found",
        2,	5,	"s-block",	"87.62"],
    [39, 	"Y",	"Yttrium",	        "Ytterby, Sweden, where it was found",
        3,	5,	"d-block",	"88.906"],
    [40, 	"Zr",	"Zirconium",	    "Zircon, a mineral, from Persian zargun, 'gold-hued'",
        4,	5,	"d-block",	"91.224"],
    [41, 	"Nb",	"Niobium",	        "Niobe, daughter of king Tantalus from Greek mythology",
        5,	5,	"d-block",	"92.906"],
    [42, 	"Mo",	"Molybdenum",	    "Greek molýbdaina, 'piece of lead', from mólybdos, 'lead', due to confusion with lead ore galena (PbS)",
        6,	5,	"d-block",	"95.95"],
    [43, 	"Tc",	"Technetium",	    "Greek tekhnētós, 'artificial'",
        7,	5,	"d-block",	"[97]"],
    [44, 	"Ru",	"Ruthenium",	    "New Latin Ruthenia, 'Russia'",
        8,	5,	"d-block",	"101.07"],
    [45, 	"Rh",	"Rhodium",	        "Greek rhodóeis, 'rose-coloured', from rhódon, 'rose'",
        9,	5,	"d-block",	"102.91"],
    [46, 	"Pd",	"Palladium",	    "Pallas, an asteroid, considered a planet at the time",
        10,	5,	"d-block",	"106.42"],
    [47, 	"Ag",	"Silver",	        "English word. Symbol Ag is derived from Latin argentum",
        11,	5,	"d-block",	"107.87"],
    [48, 	"Cd",	"Cadmium",	        "New Latin cadmia, from King Kadmos",
        12,	5,	"d-block",	"112.41"],
    [49, 	"In",	"Indium",	        "Latin indicum, 'indigo', the blue colour found in its spectrum",
        13,	5,	"p-block",	"114.82"],
    [50, 	"Sn",	"Tin",	            "English word. Symbol Sn is derived from Latin stannum",
        14,	5,	"p-block",	"118.71"],
    [51, 	"Sb",	"Antimony",	        "Latin antimonium, the origin of which is uncertain: folk etymologies suggest it is derived from Greek antí ('against') + mónos ('alone'), or Old French anti-moine, 'Monk's bane', but it could plausibly be from or related to Arabic ʾiṯmid, 'antimony', reformatted as a Latin word. Symbol Sb is derived from Latin stibium 'stibnite'",
        15,	5,	"p-block",	"121.76"],
    [52, 	"Te",	"Tellurium",	    "Latin tellus, 'the ground, earth'",
        16,	5,	"p-block",	"127.60"],
    [53, 	"I",	"Iodine",	        "French iode, from Greek ioeidḗs, 'violet'",
        17,	5,	"p-block",	"126.90"],
    [54, 	"Xe",	"Xenon",	        "Greek xénon, neuter form of xénos 'strange'",
        18,	5,	"p-block",	"131.29"],
    [55, 	"Cs",	"Caesium",	        "Latin caesius, 'sky-blue'",
        1,	6,	"s-block",	"132.91"],
    [56, 	"Ba",	"Barium",	        "Greek barýs, 'heavy'",
        2,	6,	"s-block",	"137.33"],
    [57, 	"La",	"Lanthanum",	    "Greek lanthánein, 'to lie hidden'",
        "n/a",	6,	"f-block",	"138.91"],
    [58, 	"Ce",	"Cerium",	        "Ceres, a dwarf planet, considered a planet at the time",
        "n/a",	6,	"f-block",	"140.12"],
    [59, 	"Pr",	"Praseodymium",	    "Greek prásios dídymos, 'green twin'",
        "n/a",	6,	"f-block",	"140.91"],
    [60, 	"Nd",	"Neodymium",	    "Greek néos dídymos, 'new twin'",
        "n/a",	6,	"f-block",	"144.24"],
    [61, 	"Pm",	"Promethium",	    "Prometheus, a figure in Greek mythology",
        "n/a",	6,	"f-block",	"[145]"],
    [62, 	"Sm",	"Samarium",	        "Samarskite, a mineral named after V. Samarsky-Bykhovets, Russian mine official",
        "n/a",	6,	"f-block",	"150.36"],
    [63, 	"Eu",	"Europium",	        "Europe",
        "n/a",	6,	"f-block",	"151.96"],
    [64, 	"Gd",	"Gadolinium",	    "Gadolinite, a mineral named after Johan Gadolin, Finnish chemist, physicist and mineralogist",
        "n/a",	6,	"f-block",	"157.25"],
    [65, 	"Tb",	"Terbium",	        "Ytterby, Sweden, where it was found",
        "n/a",	6,	"f-block",	"158.93"],
    [66, 	"Dy",	"Dysprosium",	    "Greek dysprósitos, 'hard to get'",
        "n/a",	6,	"f-block",	"162.50"],
    [67, 	"Ho",	"Holmium",	        "New Latin Holmia, 'Stockholm'",
        "n/a",	6,	"f-block",	"164.93"],
    [68, 	"Er",	"Erbium",	        "Ytterby, Sweden, where it was found",
        "n/a",	6,	"f-block",	"167.26"],
    [69, 	"Tm",	"Thulium",	        "Thule, the ancient name for an unclear northern location",
        "n/a",	6,	"f-block",	"168.93"],
    [70, 	"Yb",	"Ytterbium",	    "Ytterby, Sweden, where it was found",
        "n/a",	6,	"f-block",	"173.05"],
    [71, 	"Lu",	"Lutetium",	        "Latin Lutetia, 'Paris'",
        3,	6,	"d-block",	"174.97"],
    [72, 	"Hf",	"Hafnium",	        "New Latin Hafnia, 'Copenhagen' (from Danish havn, harbour)",
        4,	6,	"d-block",	"178.49"],
    [73, 	"Ta",	"Tantalum",	        "King Tantalus, father of Niobe from Greek mythology",
        5,	6,	"d-block",	"180.95"],
    [74, 	"W",	"Tungsten",	        "Swedish tung sten, 'heavy stone'. Symbol W is from Wolfram, originally from Middle High German wolf-rahm 'wolf's foam' describing the mineral wolframite",
        6,	6,	"d-block",	"183.84"],
    [75, 	"Re",	"Rhenium",	        "Latin Rhenus, 'the Rhine'",
        7,	6,	"d-block",	"186.21"],
    [76, 	"Os",	"Osmium",	        "Greek osmḗ, 'smell'",
        8,	6,	"d-block",	"190.23"],
    [77, 	"Ir",	"Iridium",	        "Iris, the Greek goddess of the rainbow",
        9,	6,	"d-block",	"192.22"],
    [78, 	"Pt",	"Platinum",	        "Spanish platina, 'little silver', from plata 'silver'",
        10,	6,	"d-block",	"195.08"],
    [79, 	"Au",	"Gold",	            "English word, from the same root as 'yellow'. Symbol Au is derived from Latin aurum",
        11,	6,	"d-block",	"196.97"],
    [80, 	"Hg",	"Mercury",	        "Mercury, Roman god of commerce, communication, and luck, known for his speed and mobility. Symbol Hg is derived from its Latin name hydrargyrum, from Greek hydrárgyros, 'water-silver'",
        12,	6,	"d-block",	"200.59"],
    [81, 	"Tl",	"Thallium",	        "Greek thallós, 'green shoot or twig'",
        13,	6,	"p-block",	"204.38"],
    [82, 	"Pb",	"Lead",	            "English word, from Proto-Celtic *ɸloudom, from a root meaning 'flow'. Symbol Pb is derived from Latin plumbum",
        14,	6,	"p-block",	"207.2"],
    [83, 	"Bi",	"Bismuth",	        "German Wismut, from weiß Masse 'white mass', unless from Arabic",
        15,	6,	"p-block",	"208.98"],
    [84, 	"Po",	"Polonium",	        "Latin Polonia, 'Poland', home country of Marie Curie",
        16,	6,	"p-block",	"[209]"],
    [85, 	"At",	"Astatine",	        "Greek ástatos, 'unstable'",
        17,	6,	"p-block",	"[210]"],
    [86, 	"Rn",	"Radon",	        "Radium emanation, originally the name of the isotope Radon-222",
        18,	6,	"p-block",	"[222]"],
    [87, 	"Fr",	"Francium",	        "France, home country of discoverer Marguerite Perey",
        1,	7,	"s-block",	"[223]"],
    [88, 	"Ra",	"Radium",	        "French radium, from Latin radius, 'ray'",
        2,	7,	"s-block",	"[226]"],
    [89, 	"Ac",	"Actinium",	        "Greek aktís, 'ray'",
        "n/a",	7,	"f-block",	"[227]"],
    [90, 	"Th",	"Thorium",	        "Thor, the Scandinavian god of thunder",
        "n/a",	7,	"f-block",	"232.04"],
    [91, 	"Pa",	"Protactinium",	    "Proto- (from Greek prôtos, 'first, before') + actinium, since actinium is produced through the radioactive decay of protactinium",
        "n/a",	7,	"f-block",	"231.04"],
    [92, 	"U",	"Uranium",	        "Uranus, the seventh planet in the Solar System",
        "n/a",	7,	"f-block",	"238.03"],
    [93, 	"Np",	"Neptunium",	    "Neptune, the eighth planet in the Solar System",
        "n/a",	7,	"f-block",	"[237]"],
    [94, 	"Pu",	"Plutonium",	    "Pluto, a dwarf planet, considered a planet in the Solar System at the time",
        "n/a",	7,	"f-block",	"[244]"],
    [95, 	"Am",	"Americium",	    "The Americas, where the element was first synthesised, by analogy with its homologue europium",
        "n/a",	7,	"f-block",	"[243]"],
    [96, 	"Cm",	"Curium",	        "Pierre Curie and Marie Curie, French physicists and chemists",
        "n/a",	7,	"f-block",	"[247]"],
    [97, 	"Bk",	"Berkelium",	    "Berkeley, California, where the element was first synthesised",
        "n/a",	7,	"f-block",	"[247]"],
    [98, 	"Cf",	"Californium",	    "California, where the element was first synthesised in the LBNL laboratory",
        "n/a",	7,	"f-block",	"[251]"],
    [99, 	"Es",	"Einsteinium",	    "Albert Einstein, German physicist",
        "n/a",	7,	"f-block",	"[252]"],
    [100, 	"Fm",	"Fermium",	        "Enrico Fermi, Italian physicist",
        "n/a",	7,	"f-block",	"[257]"],
    [101, 	"Md",	"Mendelevium",	    "Dmitri Mendeleev, Russian chemist who proposed the periodic table",
        "n/a",	7,	"f-block",	"[258]"],
    [102, 	"No",	"Nobelium",	        "Alfred Nobel, Swedish chemist and engineer",
        "n/a",	7,	"f-block",	"[259]"],
    [103, 	"Lr",	"Lawrencium",	    "Ernest Lawrence, American physicist",
        3,	7,	"d-block",	"[266]"],
    [104, 	"Rf",	"Rutherfordium",	"Ernest Rutherford, chemist and physicist from New Zealand",
        4,	7,	"d-block",	"[267]"],
    [105, 	"Db",	"Dubnium",	        "Dubna, Russia, where the element was discovered in the JINR laboratory",
        5,	7,	"d-block",	"[268]"],
    [106, 	"Sg",	"Seaborgium",	    "Glenn T. Seaborg, American chemist",
        6,	7,	"d-block",	"[269]"],
    [107, 	"Bh",	"Bohrium",          "Niels Bohr, Danish physicist",
        7,	7,	"d-block",	"[270]"],
    [108, 	"Hs",	"Hassium",          "New Latin Hassia, 'Hesse', a state in Germany",
        8,	7,	"d-block",	"[269]"],
    [109, 	"Mt",	"Meitnerium",	    "Lise Meitner, Austrian physicist",
        9,	7,	"d-block",	"[278]"],
    [110, 	"Ds",	"Darmstadtium",	    "Darmstadt, Germany, where the element was first synthesised in the GSI laboratories",
        10,	7,	"d-block",	"[281]"],
    [111, 	"Rg",	"Roentgenium",	    "Wilhelm Conrad Röntgen, German physicist",
        11,	7,	"d-block",	"[282]"],
    [112, 	"Cn",	"Copernicium",	    "Nicolaus Copernicus, Polish astronomer",
        12,	7,	"d-block",	"[285]"],
    [113, 	"Nh",	"Nihonium",	        "Japanese Nihon, 'Japan', where the element was first synthesised in the Riken laboratories",
        13,	7,	"p-block",	"[286]"],
    [114, 	"Fl",	"Flerovium",	    "Flerov Laboratory of Nuclear Reactions, part of JINR, where the element was synthesised; itself named after Georgy Flyorov, Russian physicist",
        14,	7,	"p-block",	"[289]"],
    [115, 	"Mc",	"Moscovium",	    "Moscow, Russia, where the element was first synthesised in the JINR laboratories",
        15,	7,	"p-block",	"[290]"],
    [116, 	"Lv",	"Livermorium",	    "Lawrence Livermore National Laboratory in Livermore, California",
        16,	7,	"p-block",	"[293]"],
    [117, 	"Ts",	"Tennessine",	    "Tennessee, United States, where Oak Ridge National Laboratory is located",
        17,	7,	"p-block",	"[294]"],
    [118, 	"Og",	"Oganesson",	    "Yuri Oganessian, Russian physicist",
        18,	7,	"p-block",	"[294]"],
]

def PrintElementInfo(e):
    for element in ELEMENTS:
        # Match against element name, symbol, and number
        # Convert element number to string rather than prompt to number to avoid exception handling
        if e.lower() in [str(element[0]), element[1].lower(), element[2].lower()]:
            print(f"""{element[2]}: {element[1]}, atomic number {element[0]}
            Group {element[4]} period {element[5]}, Block {element[6]}
            Atomic weight: {element[7]}
            Origin of name: {element[3]}""")
            return
    print("Element not found")

PrintElementInfo(input("Enter the name, symbol, or atomic number of an element: "))